handle missing DNS -- hardcoded CDN url
fixes
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d3n43jef99gosn.cloudfront.net', port=443): Max retries exceeded with url: /static/bower_components/tinymce/plugins/emoticons/img/smiley-sealed.gif